### ISSUE TITLE
Input layer not found: InceptionResnetV1/Repeat/block35_5/Relu in function 'connect'

### ISSUE THREAD

**Issue by VenkatKrish17** [TanFluent/facenet_opencv_dnn#1]
I followed the same steps mentioned in the repository and i ended up at this issue and i am unable to predict. 

> OpenCV(4.0.0) /home/venkat/OPENCV4/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:497: error: (-2:Unspecified error) Input layer not found: InceptionResnetV1/Repeat/block35_5/Relu in function 'connect'

System environment
Linux(Ubuntu)
Opencv (4.0.0)
Language - C++

**Comment by TanFluent** [comment]
> I followed the same steps mentioned in the repository and i ended up at this issue and i am unable to predict.
> 
> > OpenCV(4.0.0) /home/venkat/OPENCV4/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:497: error: (-2:Unspecified error) Input layer not found: InceptionResnetV1/Repeat/block35_5/Relu in function 'connect'
> 
> System environment
> Linux(Ubuntu)
> Opencv (4.0.0)
> Language - C++


hi, cuz your code is not post here. So, let me guess.
First,
it seems like you use "cv2.dnn.readNetFromTensorflow(pb_model_path, pb_txt_path)" API
to initilize tf model in opencv-dnn which i don't recomanded. I use  "cv2.dnn.readNetFromTensorflow(pb_model_path)" instead.

Second,
I mannually remove same nodes in pbtxt. these may cause this issue. check "convert_tf_pb_to_cv_pb.py" for more detail plz.


plz，post your code here if possible, so i can do more
help

**Comment by kapildevkumar** [comment]
I just cloned the repo and am following the 3 steps given. I got the same error like @VenkatKrish17. It worked when I switched to OpenCV 4.2.0
