### ISSUE TITLE
inference using BlobFromImages 

### ISSUE THREAD

**Issue by Lahirevinod** [TanFluent/facenet_opencv_dnn#3]
Hey @TanFluent  
Thanks for so detailed description about porting and inference , appreciated
I intended to use same for c++ with only OpenCV dependency ; so 4D conversion has to be done from 
blobfromImage. 
Here as you know we need scale and mean for preprocessing (prewhiten in facenet) .
here is my code for inference 
for theory i followed [Pyimagesearch](https://www.pyimagesearch.com/2017/11/06/deep-learning-opencvs-blobfromimage-works/) 

` def scalefactor(x):`
   ` std = np.std(x)`
    `std_dev = np.maximum(std, 1.0 / np.sqrt(x.size))`
   ` return std_dev`

`cvNet = load_model(model_path)`

`im = cv2.imread(face_image_path)`
`cv_mean = [np.mean(im[0]), np.mean(im[1]), np.mean(im[2])]`
`std_dev = scalefactor(im)`
`cvNet.setInput(cv2.dnn.blobFromImage(im,1/std_dev, size=(160, 160),mean=cv_mean, swapRB=True, crop=False))`
`f1 = cvNet.forward() `
 
but results are not matching with your implementation and this one , 
am i missing something? ; insight is appreciated

**Comment by Lahirevinod** [comment]
Hey @TanFluent  
I got close results by adding avg mean like follows, hope it may help someone!!!

` def scalefactor(x):`
   ` std = np.std(x)`
    `std_dev = np.maximum(std, 1.0 / np.sqrt(x.size))`
   ` return std_dev`

`cvNet = load_model(model_path)`

`im = cv2.imread(face_image_path)`
`cv_mean = [np.mean(im), np.mean(im), np.mean(im)]`
`std_dev = scalefactor(im)`
`cvNet.setInput(cv2.dnn.blobFromImage(im,1/std_dev, size=(160, 160),mean=cv_mean, swapRB=True, crop=False))`
`f1 = cvNet.forward() `

**Comment by TanFluent** [comment]
@Lahirevinod cool
