### ISSUE TITLE
pb file error

### ISSUE THREAD

**Issue by opentld** [TanFluent/facenet_opencv_dnn#4]
I try to implement your code in C++. According to the method you said, use convert_variable_to_constant.py and convert_tf_pb_to_cv_pb.py to generate the graph_final.pb file, but the graph_final.pb file cannot be opened with opencv, and the error is as follows:
OpenCV(4.4.0-dev) opencv-master\modules\dnn\src\caffe\caffe_io.cpp:1133: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "graph_final.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'
If use the original 20180402-114759.pb file, opencv can read it, but it will report an error during inference:
OpenCV(4.4.0-dev) Error: Unspecified error (Can't create layer "batch_join/fifo_queue" of type "FIFOQueueV2") in cv::dnn::dnn4_v20200609::LayerData::getLayerInstance, file opencv-master\modules\dnn\src\dnn.cpp, line 604

Here is my code.
Can you help me solve this problem? @TanFluent 
------------------------------------------------------------------------------------------------------------------
#include <iostream>
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;
using namespace cv::dnn;

void main()
{
	Net facenet;
	
	try
	{
		facenet = readNet("graph_final.pb", "graph_final.pbtxt");
	}
	catch (Exception& e)
	{
		cout << e.what() << endl;
	}

	if (facenet.empty())
	{
		cout << "error in reading models " << endl;
		return;
	}

    facenet.setPreferableBackend(DNN_BACKEND_CUDA);
    facenet.setPreferableTarget(DNN_TARGET_CUDA);

    Mat img = imread("test.jpg");

	Mat temp = img.reshape(1, img.rows * 3);

	Mat mean3;
	Mat stddev3;
	meanStdDev(temp, mean3, stddev3);
	double mean_pxl = mean3.at<double>(0);
	double stddev_pxl = stddev3.at<double>(0);

	Mat inputBlob = blobFromImages(img, 1 / stddev_pxl, Size(160, 160), mean_pxl, true, false);
	facenet.setInput(inputBlob);
	Mat outMat = facenet.forward();

	cout << outMat << endl;
	waitKey();

}

**Comment by TanFluent** [comment]
@opentld try OpenCV 4.1.2。API for cv4.4 maybe change. My code is out of date, should be updated someday. LOL
